### ISSUE TITLE
Why check for "mailEnabled" when checking for security groups?

### ISSUE THREAD

**Issue by gdubya** [grusin-db/uc-azure-account-scim-sync-py#9]
Why does the script only process "Security groups" specifically, and exclude "Microsoft 365 groups" and "mail-enabled security groups"? Are there any potential problems caused by changing the checks? For example
From:
`            if group_info.get('mailEnabled') == False and group_info.get('securityEnabled') == True:
`
To:
`            if group_info.get('securityEnabled'):
`

Testing with some dry-runs locally with these changes seems to fix an issue we see where some mail-enabled security groups that have been synced from on-prem AD to Entra are not included in the SCIM sync

**Comment by grusin-db** [comment]
There should not specific problems per say, just the volume, the reason why I have originally excluded email groups was just a vast amount of them.

There is SCIM API limit of how many groups there can be (soft limit of 5k by default, there is possibility of extending that)

Probably I there should be flag added to sync process to define which group types should be synced.
